/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://jk4nisrh25bp5kqcj4feim3mea.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sdzqs6pr2jfgdoyvrzeox2juam",
    "aws_cognito_identity_pool_id": "eu-central-1:61d5ee46-e0ea-4820-b85b-28c9a4199b87",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_GfsEiowGG",
    "aws_user_pools_web_client_id": "19djgt1rcomrou6fh3gevu7o6k",
    "oauth": {
        "domain": "teu83aosjg6j-dev.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "yordam://",
        "redirectSignOut": "yordam://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": [
            "REQUIRES_NUMBERS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "yordam-media164506-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
